management.endpoints.web.exposure.include: [refresh,health,info]
logging:
  config: ${LOGGING_CONFIG:classpath:logback-logstash.xml}
  level.com.founder.ark.ids: trace
redis:
  host: redis
  port: 6379
  check: false
ids.home.url: http://ids-admin.fzyun.io
kb.home.url: http://kb.fzyun.net

##### KEYCLOAK #####
keycloak:
  realm: ${KEYCLOAK_REALM} #REQUIRED
  auth-server-url: ${AUTH_SERVER_URL} #REQUIRED
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT} #REQUIRED
  credentials.secret: ${CLIENT_SECRET} #REQUIRED
  security-constraints[0]: #Secure the app by intercepting all requests with Keycloak
    auth-roles[0]: uma_authorization
    security-collections[0].patterns[0]: /*
  policy-enforcer-config: #Enable policy enforcer
    on-deny-redirect-to: /accessDenied
    enforcement-mode: ENFORCING
  cors: true
  enabled: false

##### AVATAR: KEYCLOAK-ADMIN-CLIENT #####
avatar:
  keycloak:
    master-realm: ${KEYCLOAK_ADMINREALM:master}
    admin-client: ${KEYCLOA_ADMINCLIENT:admin-cli}
    server-url: ${keycloak.auth-server-url}
    username: ${KEYCLOAK_USER} #REQUIRED
    password: ${KEYCLOAK_PASSWORD} #REQUIRED
    realm: ${keycloak.realm}
eureka.client.service-url:
  defaultZone: ${EUREKA_SERVER_URL:http://registry.service-governance/eureka}
eureka.instance.hostname: ${EUREKA_HOSTNAME:${spring.application.name}.avatar}

###### Spring H2 Database 设置 (如果用MySQL请替换这里的设置)######
spring:
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq.rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirms: true
    virtual-host: /
logstash.destination: elk.service-governance:5044
