management.endpoints.web.exposure.include: '*'
logging:
  config: classpath:logback-spring.xml
  level.com.founder.ark.ids: trace
redis:
  host: redis
  port: 6379
  check: false
ids.home.url: http://ids-admin.fzyun.io
kb.home.url: http://kb.fzyun.net

##### KEYCLOAK #####
keycloak:
  realm: Founder
  auth-server-url: http://auth.stage.fzyun.io/auth
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT} #REQUIRED
  credentials.secret: ${CLIENT_SECRET} #REQUIRED
  security-constraints[0]: #Secure the app by intercepting all requests with Keycloak
    auth-roles[0]: uma_authorization
    security-collections[0].patterns[0]: /*
  policy-enforcer-config: #Enable policy enforcer
    on-deny-redirect-to: /accessDenied
    enforcement-mode: ENFORCING
  enabled: false

##### AVATAR: KEYCLOAK-ADMIN-CLIENT #####
avatar:
  keycloak:
    admin-realm: master
    client: admin-cli
    serverUrl: http://auth.stage.fzyun.io/auth
    username: ${KEYCLOAK_USER:admin} #REQUIRED
    password: ${KEYCLOAK_PASSWORD} #REQUIRED
    realm: ${KEYCLOAK_REALM:Founder}
eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka

###### Spring H2 Database 设置 (如果用MySQL请替换这里的设置)######
spring:
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq.rabbitmq.stage.fzyun.io}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirms: true
    virtual-host: /
